import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

const DEFAULTS = Object.freeze({ kind: 'note', scope: 'project', namespace: 'default', importance: 0.5, confidence: 1 });
const KINDS = new Set(['note', 'decision', 'preference', 'fact', 'instruction']);
const SCOPES = new Set(['project', 'global']);
const ORDER_FIELDS = new Set(['id', 'created_at', 'updated_at', 'importance', 'confidence']);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const SLUG = /^[a-z][a-z0-9-]*$/;
const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const SCHEMA_VERSION = 1;
const SCHEMA = `
  CREATE TABLE nmnm_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL) STRICT;
  CREATE TABLE memories (
    id TEXT PRIMARY KEY, content TEXT NOT NULL, kind TEXT NOT NULL, scope TEXT NOT NULL,
    namespace TEXT NOT NULL, importance REAL NOT NULL, confidence REAL NOT NULL,
    created_at TEXT NOT NULL, updated_at TEXT NOT NULL, expires_at TEXT, removed_at TEXT,
    metadata TEXT NOT NULL
  ) STRICT;
  CREATE TABLE memory_tags (
    memory_id TEXT NOT NULL REFERENCES memories(id), tag TEXT NOT NULL,
    PRIMARY KEY (memory_id, tag)
  ) STRICT;
  CREATE VIRTUAL TABLE memories_fts USING fts5(content);
  INSERT INTO nmnm_meta(key, value) VALUES ('schema_version', '${SCHEMA_VERSION}');
`;
const SCHEMA_COLUMNS = {
  nmnm_meta: ['key', 'value'],
  memories: ['id', 'content', 'kind', 'scope', 'namespace', 'importance', 'confidence', 'created_at', 'updated_at', 'expires_at', 'removed_at', 'metadata'],
  memory_tags: ['memory_id', 'tag'],
  memories_fts: ['content'],
};
const MIGRATIONS = new Map();

function text(value, name) {
  if (typeof value !== 'string' || !value.trim()) throw new TypeError(`${name} must be a non-empty string`);
  return value.trim();
}

function kind(value) {
  const normalized = text(value, 'kind');
  if (!KINDS.has(normalized)) throw new TypeError('kind must be note, decision, preference, fact, or instruction');
  return normalized;
}

function scope(value) {
  const normalized = text(value, 'scope');
  if (!SCOPES.has(normalized)) throw new TypeError('scope must be project or global');
  return normalized;
}

function slug(value, name) {
  const normalized = text(value, name);
  if (!SLUG.test(normalized)) throw new TypeError(`${name} must be a lowercase kebab-case slug`);
  return normalized;
}

function memoryId(value) {
  const normalized = text(value, 'id');
  if (!UUID.test(normalized)) throw new TypeError('id must be a UUID generated by nanomneme');
  return normalized;
}

function score(value, name) {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 1) throw new RangeError(`${name} must be a number between 0 and 1`);
  return value;
}

function date(value, name) {
  if (value == null) return null;
  if (typeof value !== 'string' || !TIMESTAMP.test(value) || Number.isNaN(Date.parse(value))) throw new TypeError(`${name} must be a UTC ISO-8601 timestamp`);
  return value;
}

function metadata(value) {
  if (value == null) return {};
  if (typeof value !== 'object' || Array.isArray(value)) throw new TypeError('metadata must be a JSON object');
  try { return JSON.parse(JSON.stringify(value)); } catch { throw new TypeError('metadata must be JSON-serializable'); }
}

function tags(value) {
  if (value == null) return [];
  if (!Array.isArray(value)) throw new TypeError('tags must be an array of non-empty strings');
  return [...new Set(value.map((tag) => slug(tag, 'tag')))].sort();
}

function list(value, name) {
  if (value == null) return [];
  return [...new Set((Array.isArray(value) ? value : [value]).map((item) => text(item, name)))];
}

function range(value, name) {
  if (value == null) return [];
  if (typeof value === 'number') return [['=', score(value, name)]];
  if (typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${name} must be a number or range object`);
  const operators = { gt: '>', gte: '>=', lt: '<', lte: '<=' };
  const entries = Object.entries(value);
  if (!entries.length || entries.some(([key]) => !operators[key])) throw new TypeError(`${name} range has unsupported operator`);
  return entries.map(([key, item]) => [operators[key], score(item, name)]);
}

function integer(value, name, fallback, minimum) {
  if (value == null) return fallback;
  if (!Number.isInteger(value) || value < minimum || value > 1000) throw new RangeError(`${name} must be an integer between ${minimum} and 1000`);
  return value;
}

function schemaVersion(db) {
  const meta = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'nmnm_meta'").get();
  if (!meta) throw new Error('database is not a versioned nanomneme database');
  const row = db.prepare("SELECT value FROM nmnm_meta WHERE key = 'schema_version'").get();
  if (!row || !/^[1-9]\d*$/.test(row.value)) throw new Error('database has an invalid nanomneme schema_version');
  return Number(row.value);
}

function migrate(db, version) {
  let current = version;
  while (current < SCHEMA_VERSION) {
    const migration = MIGRATIONS.get(current);
    if (!migration) throw new Error(`database schema version ${current} has no migration path to ${SCHEMA_VERSION}`);
    db.exec('BEGIN IMMEDIATE');
    try {
      migration(db);
      current += 1;
      db.prepare("UPDATE nmnm_meta SET value = ? WHERE key = 'schema_version'").run(String(current));
      db.exec('COMMIT');
    } catch (error) {
      db.exec('ROLLBACK');
      throw error;
    }
  }
  return current;
}

function issueReporter() {
  const issues = new Map();
  return {
    add(code, id = null) {
      const issue = issues.get(code) ?? { code, count: 0, ids: [] };
      issue.count += 1;
      if (id != null) issue.ids.push(String(id));
      issues.set(code, issue);
    },
    list() {
      return [...issues.values()]
        .map((issue) => ({ ...issue, ids: [...new Set(issue.ids)].sort() }))
        .sort((left, right) => left.code.localeCompare(right.code));
    },
  };
}

function importedRecord(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError('import records must be objects');
  for (const field of ['id', 'content', 'kind', 'scope', 'namespace', 'importance', 'confidence', 'created_at', 'updated_at', 'expires_at', 'removed_at', 'metadata', 'tags']) {
    if (!Object.hasOwn(value, field)) throw new TypeError(`import record is missing ${field}`);
  }
  const createdAt = date(value.created_at, 'created_at');
  const updatedAt = date(value.updated_at, 'updated_at');
  if (!createdAt || !updatedAt) throw new TypeError('import record timestamps are required');
  return {
    id: memoryId(value.id),
    content: text(value.content, 'content'),
    kind: kind(value.kind),
    scope: scope(value.scope),
    namespace: slug(value.namespace, 'namespace'),
    importance: score(value.importance, 'importance'),
    confidence: score(value.confidence, 'confidence'),
    created_at: createdAt,
    updated_at: updatedAt,
    expires_at: date(value.expires_at, 'expires_at'),
    removed_at: date(value.removed_at, 'removed_at'),
    metadata: metadata(value.metadata),
    tags: tags(value.tags),
  };
}

export function open(path, { create = true } = {}) {
  text(path, 'path');
  if (typeof create !== 'boolean') throw new TypeError('create must be a boolean');
  const fresh = !existsSync(path);
  if (fresh && !create) throw new Error(`database does not exist: ${path}`);
  if (fresh) mkdirSync(dirname(path), { recursive: true });
  const db = new DatabaseSync(path, { timeout: 5000 });
  try {
    db.exec('PRAGMA foreign_keys = ON;');
    const version = fresh ? (db.exec(SCHEMA), SCHEMA_VERSION) : schemaVersion(db);
    if (version > SCHEMA_VERSION) throw new Error(`database schema version ${version} is newer than this version of nanomneme`);
    migrate(db, version);
  } catch (error) {
    db.close();
    if (fresh && /fts5/i.test(error.message)) throw new Error('SQLite FTS5 support is required', { cause: error });
    throw error;
  }

  const active = 'm.removed_at IS NULL AND (m.expires_at IS NULL OR m.expires_at > ?)';
  const hydrate = (row) => {
    const memoryTags = db.prepare('SELECT tag FROM memory_tags WHERE memory_id = ? ORDER BY tag').all(row.id).map(({ tag }) => tag);
    const memory = { ...row, metadata: JSON.parse(row.metadata), tags: memoryTags };
    if (memory.score == null) delete memory.score;
    return memory;
  };
  const read = (id, activeOnly = true) => {
    const targetId = memoryId(id);
    const row = activeOnly
      ? db.prepare(`SELECT * FROM memories m WHERE m.id = ? AND ${active}`).get(targetId, new Date().toISOString())
      : db.prepare('SELECT * FROM memories m WHERE m.id = ?').get(targetId);
    return row ? hydrate(row) : null;
  };
  const transaction = (work) => {
    db.exec('BEGIN IMMEDIATE');
    try { const result = work(); db.exec('COMMIT'); return result; } catch (error) { db.exec('ROLLBACK'); throw error; }
  };
  const writeTags = (id, nextTags) => {
    db.prepare('DELETE FROM memory_tags WHERE memory_id = ?').run(id);
    const insert = db.prepare('INSERT INTO memory_tags(memory_id, tag) VALUES (?, ?)');
    for (const tag of nextTags) insert.run(id, tag);
  };
  const syncFts = (id, content) => {
    const { rowid } = db.prepare('SELECT rowid FROM memories WHERE id = ?').get(id);
    db.prepare('DELETE FROM memories_fts WHERE rowid = ?').run(rowid);
    db.prepare('INSERT INTO memories_fts(rowid, content) VALUES (?, ?)').run(rowid, content);
  };

  return {
    retain(input) {
      if (!input || typeof input !== 'object' || Array.isArray(input)) throw new TypeError('retain input must be an object');
      const now = new Date().toISOString();
      if (input.id != null) {
        const id = memoryId(input.id);
        const current = read(id, false);
        if (!current) throw new RangeError(`memory ${id} does not exist`);
        const next = {
          content: input.content === undefined ? current.content : text(input.content, 'content'),
          kind: input.kind === undefined ? current.kind : kind(input.kind),
          scope: input.scope === undefined ? current.scope : scope(input.scope),
          namespace: input.namespace === undefined ? current.namespace : slug(input.namespace, 'namespace'),
          importance: input.importance === undefined ? current.importance : score(input.importance, 'importance'),
          confidence: input.confidence === undefined ? current.confidence : score(input.confidence, 'confidence'),
          expires_at: input.expires_at === undefined ? current.expires_at : date(input.expires_at, 'expires_at'),
          metadata: input.metadata === undefined ? current.metadata : metadata(input.metadata),
          tags: input.tags === undefined ? current.tags : tags(input.tags),
        };
        transaction(() => {
          db.prepare(`UPDATE memories SET content = ?, kind = ?, scope = ?, namespace = ?, importance = ?, confidence = ?, updated_at = ?, expires_at = ?, removed_at = NULL, metadata = ? WHERE id = ?`)
            .run(next.content, next.kind, next.scope, next.namespace, next.importance, next.confidence, now, next.expires_at, JSON.stringify(next.metadata), id);
          writeTags(id, next.tags);
          syncFts(id, next.content);
        });
        return read(id, false);
      }

      const next = {
        content: text(input.content, 'content'),
        kind: input.kind === undefined ? DEFAULTS.kind : kind(input.kind),
        scope: input.scope === undefined ? DEFAULTS.scope : scope(input.scope),
        namespace: input.namespace === undefined ? DEFAULTS.namespace : slug(input.namespace, 'namespace'),
        importance: input.importance === undefined ? DEFAULTS.importance : score(input.importance, 'importance'),
        confidence: input.confidence === undefined ? DEFAULTS.confidence : score(input.confidence, 'confidence'),
        expires_at: date(input.expires_at, 'expires_at'),
        metadata: metadata(input.metadata),
        tags: tags(input.tags),
      };
      const id = randomUUID();
      transaction(() => {
        db.prepare(`INSERT INTO memories (id, content, kind, scope, namespace, importance, confidence, created_at, updated_at, expires_at, removed_at, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?)`)
          .run(id, next.content, next.kind, next.scope, next.namespace, next.importance, next.confidence, now, now, next.expires_at, JSON.stringify(next.metadata));
        writeTags(id, next.tags);
        syncFts(id, next.content);
      });
      return read(id, false);
    },

    recall({ id }) {
      return read(memoryId(id));
    },

    retrieve(selector = {}) {
      if (!selector || typeof selector !== 'object' || Array.isArray(selector)) throw new TypeError('retrieve selector must be an object');
      const query = selector.query == null ? null : text(selector.query, 'query');
      const limit = integer(selector.limit, 'limit', 20, 1);
      const offset = integer(selector.offset, 'offset', 0, 0);
      const expires = selector.expires ?? 'active';
      if (!['active', 'expired', 'any'].includes(expires)) throw new TypeError('expires must be active, expired, or any');
      const where = ['m.removed_at IS NULL'];
      const parameters = [];
      if (expires === 'active') {
        where.push('(m.expires_at IS NULL OR m.expires_at > ?)');
        parameters.push(new Date().toISOString());
      } else if (expires === 'expired') {
        where.push('m.expires_at IS NOT NULL AND m.expires_at <= ?');
        parameters.push(new Date().toISOString());
      }
      const join = query ? 'JOIN memories_fts ON memories_fts.rowid = m.rowid' : '';
      if (query) { where.push('memories_fts MATCH ?'); parameters.push(query); }
      for (const [field, value] of [['kind', selector.kind], ['scope', selector.scope], ['namespace', selector.namespace]]) {
        const values = list(value, field);
        if (field === 'kind') values.forEach(kind);
        if (field === 'scope') values.forEach(scope);
        if (field === 'namespace') values.forEach((value) => slug(value, 'namespace'));
        if (values.length) { where.push(`m.${field} IN (${values.map(() => '?').join(', ')})`); parameters.push(...values); }
      }
      const wantedTags = tags(selector.tags);
      if (wantedTags.length) {
        where.push(`m.id IN (SELECT memory_id FROM memory_tags WHERE tag IN (${wantedTags.map(() => '?').join(', ')}) GROUP BY memory_id HAVING COUNT(DISTINCT tag) = ?)`);
        parameters.push(...wantedTags, wantedTags.length);
      }
      for (const [field, value] of [['importance', selector.importance], ['confidence', selector.confidence]]) {
        for (const [operator, target] of range(value, field)) { where.push(`m.${field} ${operator} ?`); parameters.push(target); }
      }
      const orderBy = selector.order_by ?? (query ? 'relevance' : 'updated_at');
      const ordering = orderBy === 'relevance' && query
        ? 'score ASC, m.id ASC'
        : ORDER_FIELDS.has(orderBy)
          ? `m.${orderBy} ${orderBy === 'updated_at' ? 'DESC' : 'ASC'}, m.id ASC`
          : null;
      if (!ordering) throw new TypeError('order_by must be relevance, id, created_at, updated_at, importance, or confidence');
      const condition = where.join(' AND ');
      try {
        const total = db.prepare(`SELECT COUNT(*) AS total FROM memories m ${join} WHERE ${condition}`).get(...parameters).total;
        const rows = db.prepare(`SELECT m.*, ${query ? 'bm25(memories_fts) AS score' : 'NULL AS score'} FROM memories m ${join} WHERE ${condition} ORDER BY ${ordering} LIMIT ? OFFSET ?`)
          .all(...parameters, limit, offset);
        return { total, items: rows.map(hydrate) };
      } catch (error) {
        if (query) throw new TypeError(`invalid FTS5 query: ${error.message}`);
        throw error;
      }
    },

    export() {
      return db.prepare('SELECT * FROM memories ORDER BY id').all().map(hydrate).map(({ score: _score, ...memory }) => memory);
    },

    import(records) {
      if (!Array.isArray(records)) throw new TypeError('import records must be an array');
      const next = records.map(importedRecord);
      const ids = new Set();
      for (const record of next) {
        if (ids.has(record.id)) throw new RangeError(`import contains duplicate id ${record.id}`);
        ids.add(record.id);
        if (db.prepare('SELECT 1 FROM memories WHERE id = ?').get(record.id)) throw new RangeError(`memory ${record.id} already exists`);
      }
      transaction(() => {
        for (const record of next) {
          db.prepare(`INSERT INTO memories (id, content, kind, scope, namespace, importance, confidence, created_at, updated_at, expires_at, removed_at, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
            .run(record.id, record.content, record.kind, record.scope, record.namespace, record.importance, record.confidence, record.created_at, record.updated_at, record.expires_at, record.removed_at, JSON.stringify(record.metadata));
          writeTags(record.id, record.tags);
          if (record.removed_at == null) syncFts(record.id, record.content);
        }
      });
      return { imported: next.length };
    },

    rebuildFts() {
      const ftsSchema = db.prepare("SELECT sql FROM sqlite_master WHERE name = 'memories_fts'").get();
      if (!ftsSchema || !/^CREATE VIRTUAL TABLE\s+memories_fts\s+USING\s+fts5\b/i.test(ftsSchema.sql)) throw new Error('a valid SQLite FTS5 table is required to rebuild FTS');
      const rebuilt = db.prepare('SELECT COUNT(*) AS count FROM memories WHERE removed_at IS NULL').get().count;
      transaction(() => {
        db.exec('DELETE FROM memories_fts');
        db.exec('INSERT INTO memories_fts(rowid, content) SELECT rowid, content FROM memories WHERE removed_at IS NULL');
      });
      return { mode: 'rebuild-fts', rebuilt };
    },

    verify() {
      const report = issueReporter();
      const tables = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").all().map(({ name }) => name);
      for (const [table, columns] of Object.entries(SCHEMA_COLUMNS)) {
        if (!tables.includes(table)) {
          report.add('schema_missing', table);
          continue;
        }
        const actual = db.prepare(`PRAGMA table_info(${table})`).all().map(({ name }) => name);
        if (columns.some((column) => !actual.includes(column))) report.add('schema_columns', table);
      }
      const ftsSchema = db.prepare("SELECT sql FROM sqlite_master WHERE name = 'memories_fts'").get();
      if (ftsSchema && !/^CREATE VIRTUAL TABLE\s+memories_fts\s+USING\s+fts5\b/i.test(ftsSchema.sql)) report.add('schema_fts', 'memories_fts');
      for (const row of db.prepare('PRAGMA integrity_check').all()) {
        const value = Object.values(row)[0];
        if (value !== 'ok') report.add('sqlite_integrity');
      }
      for (const row of db.prepare('PRAGMA foreign_key_check').all()) report.add('foreign_key', `${row.table}:${row.rowid}`);

      const memories = tables.includes('memories')
        ? db.prepare('SELECT rowid, * FROM memories ORDER BY id').all()
        : [];
      for (const memory of memories) {
        try {
          memoryId(memory.id);
          text(memory.content, 'content');
          kind(memory.kind);
          scope(memory.scope);
          slug(memory.namespace, 'namespace');
          score(memory.importance, 'importance');
          score(memory.confidence, 'confidence');
          date(memory.created_at, 'created_at');
          date(memory.updated_at, 'updated_at');
          date(memory.expires_at, 'expires_at');
          date(memory.removed_at, 'removed_at');
          metadata(JSON.parse(memory.metadata));
        } catch {
          report.add('memory_field', memory.id);
        }
      }
      if (tables.includes('memory_tags')) {
        for (const tag of db.prepare('SELECT memory_id, tag FROM memory_tags ORDER BY memory_id, tag').all()) {
          try { memoryId(tag.memory_id); slug(tag.tag, 'tag'); } catch { report.add('tag_field', tag.memory_id); }
        }
      }
      if (tables.includes('memories_fts') && tables.includes('memories')) {
        const fts = new Map(db.prepare('SELECT rowid, content FROM memories_fts').all().map((row) => [row.rowid, row]));
        for (const memory of memories) {
          const indexed = fts.get(memory.rowid);
          fts.delete(memory.rowid);
          if (memory.removed_at != null && indexed) report.add('fts_removed', memory.id);
          else if (memory.removed_at == null && !indexed) report.add('fts_missing', memory.id);
          else if (indexed && indexed.content !== memory.content) report.add('fts_mismatch', memory.id);
        }
        for (const rowid of fts.keys()) report.add('fts_orphan', rowid);
      }
      const issues = report.list();
      return { ok: issues.length === 0, schema_version: SCHEMA_VERSION, issues };
    },

    remove({ id, mode = 'soft' }) {
      if (!['soft', 'purge'].includes(mode)) throw new TypeError('mode must be soft or purge');
      const memory = read(memoryId(id), mode === 'soft');
      if (!memory) return null;
      const timestamp = new Date().toISOString();
      transaction(() => {
        db.prepare('DELETE FROM memories_fts WHERE rowid = (SELECT rowid FROM memories WHERE id = ?)').run(memory.id);
        if (mode === 'purge') {
          db.prepare('DELETE FROM memory_tags WHERE memory_id = ?').run(memory.id);
          db.prepare('DELETE FROM memories WHERE id = ?').run(memory.id);
        } else {
          db.prepare('UPDATE memories SET removed_at = ?, updated_at = ? WHERE id = ?').run(timestamp, timestamp, memory.id);
        }
      });
      return mode === 'purge'
        ? { id: memory.id, mode, purged_at: timestamp }
        : { id: memory.id, mode, removed_at: timestamp };
    },

    close() { db.close(); },
  };
}
