import { randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

const DEFAULTS = Object.freeze({ kind: 'note', scope: 'project', namespace: 'default', importance: 0.5, confidence: 1 });
const KINDS = new Set(['note', 'decision', 'preference', 'fact', 'instruction']);
const SCOPES = new Set(['project', 'global']);
const ORDER_FIELDS = new Set(['id', 'created_at', 'updated_at', 'importance', 'confidence']);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const SLUG = /^[a-z][a-z0-9-]*$/;
const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;

function text(value, name) {
  if (typeof value !== 'string' || !value.trim()) throw new TypeError(`${name} must be a non-empty string`);
  return value.trim();
}

function kind(value) {
  const normalized = text(value, 'kind');
  if (!KINDS.has(normalized)) throw new TypeError('kind must be note, decision, preference, fact, or instruction');
  return normalized;
}

function scope(value) {
  const normalized = text(value, 'scope');
  if (!SCOPES.has(normalized)) throw new TypeError('scope must be project or global');
  return normalized;
}

function slug(value, name) {
  const normalized = text(value, name);
  if (!SLUG.test(normalized)) throw new TypeError(`${name} must be a lowercase kebab-case slug`);
  return normalized;
}

function memoryId(value) {
  const normalized = text(value, 'id');
  if (!UUID.test(normalized)) throw new TypeError('id must be a UUID generated by nanomneme');
  return normalized;
}

function score(value, name) {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 1) throw new RangeError(`${name} must be a number between 0 and 1`);
  return value;
}

function date(value, name) {
  if (value == null) return null;
  if (typeof value !== 'string' || !TIMESTAMP.test(value) || Number.isNaN(Date.parse(value))) throw new TypeError(`${name} must be a UTC ISO-8601 timestamp`);
  return value;
}

function metadata(value) {
  if (value == null) return {};
  if (typeof value !== 'object' || Array.isArray(value)) throw new TypeError('metadata must be a JSON object');
  try { return JSON.parse(JSON.stringify(value)); } catch { throw new TypeError('metadata must be JSON-serializable'); }
}

function tags(value) {
  if (value == null) return [];
  if (!Array.isArray(value)) throw new TypeError('tags must be an array of non-empty strings');
  return [...new Set(value.map((tag) => slug(tag, 'tag')))].sort();
}

function list(value, name) {
  if (value == null) return [];
  return [...new Set((Array.isArray(value) ? value : [value]).map((item) => text(item, name)))];
}

function range(value, name) {
  if (value == null) return [];
  if (typeof value === 'number') return [['=', score(value, name)]];
  if (typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`${name} must be a number or range object`);
  const operators = { gt: '>', gte: '>=', lt: '<', lte: '<=' };
  const entries = Object.entries(value);
  if (!entries.length || entries.some(([key]) => !operators[key])) throw new TypeError(`${name} range has unsupported operator`);
  return entries.map(([key, item]) => [operators[key], score(item, name)]);
}

function integer(value, name, fallback, minimum) {
  if (value == null) return fallback;
  if (!Number.isInteger(value) || value < minimum || value > 1000) throw new RangeError(`${name} must be an integer between ${minimum} and 1000`);
  return value;
}

export function open(path) {
  text(path, 'path');
  mkdirSync(dirname(path), { recursive: true });
  const db = new DatabaseSync(path, { timeout: 5000 });
  db.exec(`
    PRAGMA foreign_keys = ON;
    CREATE TABLE IF NOT EXISTS nmnm_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL) STRICT;
    CREATE TABLE IF NOT EXISTS memories (
      id TEXT PRIMARY KEY, content TEXT NOT NULL, kind TEXT NOT NULL, scope TEXT NOT NULL,
      namespace TEXT NOT NULL, importance REAL NOT NULL, confidence REAL NOT NULL,
      created_at TEXT NOT NULL, updated_at TEXT NOT NULL, expires_at TEXT, removed_at TEXT,
      metadata TEXT NOT NULL
    ) STRICT;
    CREATE TABLE IF NOT EXISTS memory_tags (
      memory_id TEXT NOT NULL REFERENCES memories(id), tag TEXT NOT NULL,
      PRIMARY KEY (memory_id, tag)
    ) STRICT;
    INSERT OR IGNORE INTO nmnm_meta(key, value) VALUES ('schema_version', '1');
  `);
  try {
    db.exec('CREATE VIRTUAL TABLE IF NOT EXISTS memories_fts USING fts5(content)');
  } catch (error) {
    db.close();
    throw new Error('SQLite FTS5 support is required', { cause: error });
  }

  const active = 'm.removed_at IS NULL AND (m.expires_at IS NULL OR m.expires_at > ?)';
  const hydrate = (row) => {
    const memoryTags = db.prepare('SELECT tag FROM memory_tags WHERE memory_id = ? ORDER BY tag').all(row.id).map(({ tag }) => tag);
    const memory = { ...row, metadata: JSON.parse(row.metadata), tags: memoryTags };
    if (memory.score == null) delete memory.score;
    return memory;
  };
  const read = (id, activeOnly = true) => {
    const targetId = memoryId(id);
    const row = activeOnly
      ? db.prepare(`SELECT * FROM memories m WHERE m.id = ? AND ${active}`).get(targetId, new Date().toISOString())
      : db.prepare('SELECT * FROM memories m WHERE m.id = ?').get(targetId);
    return row ? hydrate(row) : null;
  };
  const transaction = (work) => {
    db.exec('BEGIN IMMEDIATE');
    try { const result = work(); db.exec('COMMIT'); return result; } catch (error) { db.exec('ROLLBACK'); throw error; }
  };
  const writeTags = (id, nextTags) => {
    db.prepare('DELETE FROM memory_tags WHERE memory_id = ?').run(id);
    const insert = db.prepare('INSERT INTO memory_tags(memory_id, tag) VALUES (?, ?)');
    for (const tag of nextTags) insert.run(id, tag);
  };
  const syncFts = (id, content) => {
    const { rowid } = db.prepare('SELECT rowid FROM memories WHERE id = ?').get(id);
    db.prepare('DELETE FROM memories_fts WHERE rowid = ?').run(rowid);
    db.prepare('INSERT INTO memories_fts(rowid, content) VALUES (?, ?)').run(rowid, content);
  };

  return {
    retain(input) {
      if (!input || typeof input !== 'object' || Array.isArray(input)) throw new TypeError('retain input must be an object');
      const now = new Date().toISOString();
      if (input.id != null) {
        const id = memoryId(input.id);
        const current = read(id, false);
        if (!current) throw new RangeError(`memory ${id} does not exist`);
        const next = {
          content: input.content === undefined ? current.content : text(input.content, 'content'),
          kind: input.kind === undefined ? current.kind : kind(input.kind),
          scope: input.scope === undefined ? current.scope : scope(input.scope),
          namespace: input.namespace === undefined ? current.namespace : slug(input.namespace, 'namespace'),
          importance: input.importance === undefined ? current.importance : score(input.importance, 'importance'),
          confidence: input.confidence === undefined ? current.confidence : score(input.confidence, 'confidence'),
          expires_at: input.expires_at === undefined ? current.expires_at : date(input.expires_at, 'expires_at'),
          metadata: input.metadata === undefined ? current.metadata : metadata(input.metadata),
          tags: input.tags === undefined ? current.tags : tags(input.tags),
        };
        transaction(() => {
          db.prepare(`UPDATE memories SET content = ?, kind = ?, scope = ?, namespace = ?, importance = ?, confidence = ?, updated_at = ?, expires_at = ?, removed_at = NULL, metadata = ? WHERE id = ?`)
            .run(next.content, next.kind, next.scope, next.namespace, next.importance, next.confidence, now, next.expires_at, JSON.stringify(next.metadata), id);
          writeTags(id, next.tags);
          syncFts(id, next.content);
        });
        return read(id, false);
      }

      const next = {
        content: text(input.content, 'content'),
        kind: input.kind === undefined ? DEFAULTS.kind : kind(input.kind),
        scope: input.scope === undefined ? DEFAULTS.scope : scope(input.scope),
        namespace: input.namespace === undefined ? DEFAULTS.namespace : slug(input.namespace, 'namespace'),
        importance: input.importance === undefined ? DEFAULTS.importance : score(input.importance, 'importance'),
        confidence: input.confidence === undefined ? DEFAULTS.confidence : score(input.confidence, 'confidence'),
        expires_at: date(input.expires_at, 'expires_at'),
        metadata: metadata(input.metadata),
        tags: tags(input.tags),
      };
      const id = randomUUID();
      transaction(() => {
        db.prepare(`INSERT INTO memories (id, content, kind, scope, namespace, importance, confidence, created_at, updated_at, expires_at, removed_at, metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?)`)
          .run(id, next.content, next.kind, next.scope, next.namespace, next.importance, next.confidence, now, now, next.expires_at, JSON.stringify(next.metadata));
        writeTags(id, next.tags);
        syncFts(id, next.content);
      });
      return read(id, false);
    },

    recall({ id }) {
      return read(memoryId(id));
    },

    retrieve(selector = {}) {
      if (!selector || typeof selector !== 'object' || Array.isArray(selector)) throw new TypeError('retrieve selector must be an object');
      const query = selector.query == null ? null : text(selector.query, 'query');
      const limit = integer(selector.limit, 'limit', 20, 1);
      const offset = integer(selector.offset, 'offset', 0, 0);
      const expires = selector.expires ?? 'active';
      if (!['active', 'expired', 'any'].includes(expires)) throw new TypeError('expires must be active, expired, or any');
      const where = ['m.removed_at IS NULL'];
      const parameters = [];
      if (expires === 'active') {
        where.push('(m.expires_at IS NULL OR m.expires_at > ?)');
        parameters.push(new Date().toISOString());
      } else if (expires === 'expired') {
        where.push('m.expires_at IS NOT NULL AND m.expires_at <= ?');
        parameters.push(new Date().toISOString());
      }
      const join = query ? 'JOIN memories_fts ON memories_fts.rowid = m.rowid' : '';
      if (query) { where.push('memories_fts MATCH ?'); parameters.push(query); }
      for (const [field, value] of [['kind', selector.kind], ['scope', selector.scope], ['namespace', selector.namespace]]) {
        const values = list(value, field);
        if (field === 'kind') values.forEach(kind);
        if (field === 'scope') values.forEach(scope);
        if (field === 'namespace') values.forEach((value) => slug(value, 'namespace'));
        if (values.length) { where.push(`m.${field} IN (${values.map(() => '?').join(', ')})`); parameters.push(...values); }
      }
      const wantedTags = tags(selector.tags);
      if (wantedTags.length) {
        where.push(`m.id IN (SELECT memory_id FROM memory_tags WHERE tag IN (${wantedTags.map(() => '?').join(', ')}) GROUP BY memory_id HAVING COUNT(DISTINCT tag) = ?)`);
        parameters.push(...wantedTags, wantedTags.length);
      }
      for (const [field, value] of [['importance', selector.importance], ['confidence', selector.confidence]]) {
        for (const [operator, target] of range(value, field)) { where.push(`m.${field} ${operator} ?`); parameters.push(target); }
      }
      const orderBy = selector.order_by ?? (query ? 'relevance' : 'updated_at');
      const ordering = orderBy === 'relevance' && query
        ? 'score ASC, m.id ASC'
        : ORDER_FIELDS.has(orderBy)
          ? `m.${orderBy} ${orderBy === 'updated_at' ? 'DESC' : 'ASC'}, m.id ASC`
          : null;
      if (!ordering) throw new TypeError('order_by must be relevance, id, created_at, updated_at, importance, or confidence');
      const condition = where.join(' AND ');
      try {
        const total = db.prepare(`SELECT COUNT(*) AS total FROM memories m ${join} WHERE ${condition}`).get(...parameters).total;
        const rows = db.prepare(`SELECT m.*, ${query ? 'bm25(memories_fts) AS score' : 'NULL AS score'} FROM memories m ${join} WHERE ${condition} ORDER BY ${ordering} LIMIT ? OFFSET ?`)
          .all(...parameters, limit, offset);
        return { total, items: rows.map(hydrate) };
      } catch (error) {
        if (query) throw new TypeError(`invalid FTS5 query: ${error.message}`);
        throw error;
      }
    },

    remove({ id, mode = 'soft' }) {
      if (!['soft', 'hard'].includes(mode)) throw new TypeError('mode must be soft or hard');
      const memory = read(memoryId(id), mode === 'soft');
      if (!memory) return null;
      const timestamp = new Date().toISOString();
      transaction(() => {
        db.prepare('DELETE FROM memories_fts WHERE rowid = (SELECT rowid FROM memories WHERE id = ?)').run(memory.id);
        if (mode === 'hard') {
          db.prepare('DELETE FROM memory_tags WHERE memory_id = ?').run(memory.id);
          db.prepare('DELETE FROM memories WHERE id = ?').run(memory.id);
        } else {
          db.prepare('UPDATE memories SET removed_at = ?, updated_at = ? WHERE id = ?').run(timestamp, timestamp, memory.id);
        }
      });
      return mode === 'hard'
        ? { id: memory.id, mode, purged_at: timestamp }
        : { id: memory.id, mode, removed_at: timestamp };
    },

    close() { db.close(); },
  };
}
