#!/usr/bin/env node
import { readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

function defaultTargets() {
  const provenance = JSON.parse(readFileSync(fileURLToPath(new URL('../external/logslines/PROVENANCE.json', import.meta.url)), 'utf8'));
  const license = readFileSync(fileURLToPath(new URL('../external/logslines/LICENSE', import.meta.url)), 'utf8').trimEnd();
  const jsoncLicense = readFileSync(join(dirname(createRequire(import.meta.url).resolve('jsonc-parser/package.json')), 'LICENSE.md'), 'utf8').replaceAll('\r\n', '\n').trimEnd();
  return [
    {
      name: 'Shared', entry: '../shared/logger/index.js', output: '../packages/nmnm-core/src/logging-runtime.generated.js',
      options: { external: ['jsonc-parser'] },
      banner: `/* Logslines ${provenance.tag}\n\n${license}\n*/`,
    },
    {
      name: 'UI error', entry: '../packages/nmnm-ui/src/ui-logger.js', output: '../packages/nmnm-ui/src/ui-logging-runtime.generated.js',
      options: { mainFields: ['module', 'main'] },
      banner: `/* Generated by scripts/build-logger.js. Logslines ${provenance.tag}\n\n${license.replaceAll('\r\n', '\n')}\n\nBundled jsonc-parser:\n${jsoncLicense}\n*/`,
    },
  ];
}

// Build every target before writing so compilation/read failures leave outputs intact.
export async function buildLogger({ check = false, targets, buildImpl = build } = {}) {
  targets ??= defaultTargets();
  const results = [];
  for (const target of targets) {
    const output = target.output.startsWith('../')
      ? fileURLToPath(new URL(target.output, import.meta.url)) : target.output;
    try {
      const result = await buildImpl({
        absWorkingDir: fileURLToPath(new URL('..', import.meta.url)),
        entryPoints: [target.entry?.startsWith('../') ? fileURLToPath(new URL(target.entry, import.meta.url)) : target.entry],
        outfile: output, bundle: true, platform: 'node', format: 'esm',
        target: 'node22', legalComments: 'none', ...target.options,
        ...(target.banner ? { banner: { js: target.banner } } : {}), write: false,
      });
      const generated = result.outputFiles[0].text;
      let current;
      try { current = readFileSync(output, 'utf8'); }
      catch (error) { if (error.code !== 'ENOENT') throw error; }
      results.push({ name: target.name, output, status: current === generated ? 'current' : 'stale', generated, written: false });
    } catch (error) {
      results.push({ name: target.name, output, status: 'failed', error, written: false });
    }
  }
  if (!check && !results.some(result => result.status === 'failed')) {
    for (const result of results.filter(result => result.status === 'stale')) {
      try { writeFileSync(result.output, result.generated); result.written = true; }
      catch (error) { result.status = 'failed'; result.error = error; break; }
    }
  }
  return results.map(({ generated, ...result }) => result);
}

if (process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))) {
  try {
    const args = process.argv.slice(2);
    if (args.some(arg => arg !== '--check') || args.length > 1) throw new Error('Usage: node scripts/build-logger.js [--check]');
    const results = await buildLogger({ check: args.includes('--check') });
    for (const result of results) {
      if (result.status === 'failed') console.error(`${result.name} logger build failed: ${result.error.message}`);
      else if (args.includes('--check') && result.status === 'stale') console.error(`${result.name} logger bundle is stale; run npm run logslines:build`);
    }
    process.exitCode = results.some(result => result.status === 'failed') ? 1
      : args.includes('--check') && results.some(result => result.status === 'stale') ? 2 : 0;
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
