#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const provenance = JSON.parse(readFileSync(fileURLToPath(new URL('../external/logslines/PROVENANCE.json', import.meta.url)), 'utf8'));
const license = readFileSync(fileURLToPath(new URL('../external/logslines/LICENSE', import.meta.url)), 'utf8').trimEnd();
const jsoncLicense = readFileSync(join(dirname(createRequire(import.meta.url).resolve('jsonc-parser/package.json')), 'LICENSE.md'), 'utf8').replaceAll('\r\n', '\n').trimEnd();
const targets = [
  {
    name: 'Shared', entry: '../shared/logger/index.js', output: '../packages/nmnm-core/src/logging-runtime.generated.js',
    options: { external: ['jsonc-parser'] },
    banner: `/* Logslines ${provenance.tag}\n\n${license}\n*/`,
  },
  {
    name: 'UI error', entry: '../packages/nmnm-ui/build/ui-logger.js', output: '../packages/nmnm-ui/src/ui-logging-runtime.generated.js',
    options: { mainFields: ['module', 'main'] },
    banner: `/* Generated by scripts/build-logger.js. Logslines ${provenance.tag}\n\n${license.replaceAll('\r\n', '\n')}\n\nBundled jsonc-parser:\n${jsoncLicense}\n*/`,
  },
];
for (const target of targets) {
  const output = fileURLToPath(new URL(target.output, import.meta.url));
  const result = await build({
    entryPoints: [fileURLToPath(new URL(target.entry, import.meta.url))],
    outfile: output,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    legalComments: 'none',
    ...target.options,
    banner: { js: target.banner },
    write: false,
  });
  const generated = result.outputFiles[0].text;
  if (process.argv.includes('--check')) {
    let current;
    try { current = readFileSync(output, 'utf8'); } catch { /* missing output is stale */ }
    if (current !== generated) {
      console.error(`${target.name} logger bundle is stale; run node scripts/build-logger.js`);
      process.exitCode = 1;
    }
  } else {
    writeFileSync(output, generated);
  }
}
